# Generated by Django 3.2.4 on 2021-06-13 07:53

import datetime
from django.db import migrations, models
import test_app.graphic


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=128)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('t_days', models.IntegerField()),
                ('t_hours', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 6, 13, 7, 53, 22, 109817))),
                ('text_status', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'graphic',
                'verbose_name_plural': 'graphics',
                'db_table': 'graphics',
            },
            bases=(test_app.graphic.GraphicMixin, models.Model),
        ),
    ]
