# Generated by Django 3.2.4 on 2021-06-13 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 7, 55, 10, 501461)),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='text_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
